apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-configmap
data:
    # property-like keys; each key maps to a smiple value
    player_initial_lives: "3"
    ui_filename: "user-interface.properties"

    # file-like keys
    game.properties: |
      enemy.types=aliens,monsters
      player.maximum-lives=5
      player.type={{ .Values.playerType }}
    user-interface.properties: |
      color.good=blue
      color.bad=yellow
      allow.textmode=true
